/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResumenEmpresaRouteImport } from './routes/resumen-empresa'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as EmpezarNegocioRouteImport } from './routes/empezar-negocio'
import { Route as DistribuidorRouteImport } from './routes/distribuidor'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as ProductosSlugRouteImport } from './routes/productos.$slug'
import { Route as PeptidosCiudadRouteImport } from './routes/peptidos.$ciudad'
import { Route as PagoPendienteRouteImport } from './routes/pago.pendiente'
import { Route as PagoFalloRouteImport } from './routes/pago.fallo'
import { Route as PagoExitoRouteImport } from './routes/pago.exito'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api.public.mercadopago-webhook'
import { Route as ApiCheckoutMercadopagoRouteImport } from './routes/api.checkout.mercadopago'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumenEmpresaRoute = ResumenEmpresaRouteImport.update({
  id: '/resumen-empresa',
  path: '/resumen-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpezarNegocioRoute = EmpezarNegocioRouteImport.update({
  id: '/empezar-negocio',
  path: '/empezar-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidorRoute = DistribuidorRouteImport.update({
  id: '/distribuidor',
  path: '/distribuidor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosSlugRoute = ProductosSlugRouteImport.update({
  id: '/productos/$slug',
  path: '/productos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PeptidosCiudadRoute = PeptidosCiudadRouteImport.update({
  id: '/peptidos/$ciudad',
  path: '/peptidos/$ciudad',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoPendienteRoute = PagoPendienteRouteImport.update({
  id: '/pago/pendiente',
  path: '/pago/pendiente',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoFalloRoute = PagoFalloRouteImport.update({
  id: '/pago/fallo',
  path: '/pago/fallo',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoExitoRoute = PagoExitoRouteImport.update({
  id: '/pago/exito',
  path: '/pago/exito',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCheckoutMercadopagoRoute = ApiCheckoutMercadopagoRouteImport.update({
  id: '/api/checkout/mercadopago',
  path: '/api/checkout/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/distribuidor': typeof DistribuidorRoute
  '/empezar-negocio': typeof EmpezarNegocioRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/resumen-empresa': typeof ResumenEmpresaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/fallo': typeof PagoFalloRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/peptidos/$ciudad': typeof PeptidosCiudadRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos/': typeof ProductosIndexRoute
  '/api/checkout/mercadopago': typeof ApiCheckoutMercadopagoRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/distribuidor': typeof DistribuidorRoute
  '/empezar-negocio': typeof EmpezarNegocioRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/resumen-empresa': typeof ResumenEmpresaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/fallo': typeof PagoFalloRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/peptidos/$ciudad': typeof PeptidosCiudadRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos': typeof ProductosIndexRoute
  '/api/checkout/mercadopago': typeof ApiCheckoutMercadopagoRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/distribuidor': typeof DistribuidorRoute
  '/empezar-negocio': typeof EmpezarNegocioRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/resumen-empresa': typeof ResumenEmpresaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/fallo': typeof PagoFalloRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/peptidos/$ciudad': typeof PeptidosCiudadRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos/': typeof ProductosIndexRoute
  '/api/checkout/mercadopago': typeof ApiCheckoutMercadopagoRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/como-funciona'
    | '/contacto'
    | '/distribuidor'
    | '/empezar-negocio'
    | '/preguntas-frecuentes'
    | '/resumen-empresa'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/pago/exito'
    | '/pago/fallo'
    | '/pago/pendiente'
    | '/peptidos/$ciudad'
    | '/productos/$slug'
    | '/productos/'
    | '/api/checkout/mercadopago'
    | '/api/public/mercadopago-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/como-funciona'
    | '/contacto'
    | '/distribuidor'
    | '/empezar-negocio'
    | '/preguntas-frecuentes'
    | '/resumen-empresa'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/pago/exito'
    | '/pago/fallo'
    | '/pago/pendiente'
    | '/peptidos/$ciudad'
    | '/productos/$slug'
    | '/productos'
    | '/api/checkout/mercadopago'
    | '/api/public/mercadopago-webhook'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/como-funciona'
    | '/contacto'
    | '/distribuidor'
    | '/empezar-negocio'
    | '/preguntas-frecuentes'
    | '/resumen-empresa'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/pago/exito'
    | '/pago/fallo'
    | '/pago/pendiente'
    | '/peptidos/$ciudad'
    | '/productos/$slug'
    | '/productos/'
    | '/api/checkout/mercadopago'
    | '/api/public/mercadopago-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  DistribuidorRoute: typeof DistribuidorRoute
  EmpezarNegocioRoute: typeof EmpezarNegocioRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  ResumenEmpresaRoute: typeof ResumenEmpresaRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PagoExitoRoute: typeof PagoExitoRoute
  PagoFalloRoute: typeof PagoFalloRoute
  PagoPendienteRoute: typeof PagoPendienteRoute
  PeptidosCiudadRoute: typeof PeptidosCiudadRoute
  ProductosSlugRoute: typeof ProductosSlugRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
  ApiCheckoutMercadopagoRoute: typeof ApiCheckoutMercadopagoRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumen-empresa': {
      id: '/resumen-empresa'
      path: '/resumen-empresa'
      fullPath: '/resumen-empresa'
      preLoaderRoute: typeof ResumenEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empezar-negocio': {
      id: '/empezar-negocio'
      path: '/empezar-negocio'
      fullPath: '/empezar-negocio'
      preLoaderRoute: typeof EmpezarNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor': {
      id: '/distribuidor'
      path: '/distribuidor'
      fullPath: '/distribuidor'
      preLoaderRoute: typeof DistribuidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$slug': {
      id: '/productos/$slug'
      path: '/productos/$slug'
      fullPath: '/productos/$slug'
      preLoaderRoute: typeof ProductosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peptidos/$ciudad': {
      id: '/peptidos/$ciudad'
      path: '/peptidos/$ciudad'
      fullPath: '/peptidos/$ciudad'
      preLoaderRoute: typeof PeptidosCiudadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/pendiente': {
      id: '/pago/pendiente'
      path: '/pago/pendiente'
      fullPath: '/pago/pendiente'
      preLoaderRoute: typeof PagoPendienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/fallo': {
      id: '/pago/fallo'
      path: '/pago/fallo'
      fullPath: '/pago/fallo'
      preLoaderRoute: typeof PagoFalloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/exito': {
      id: '/pago/exito'
      path: '/pago/exito'
      fullPath: '/pago/exito'
      preLoaderRoute: typeof PagoExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/mercadopago': {
      id: '/api/checkout/mercadopago'
      path: '/api/checkout/mercadopago'
      fullPath: '/api/checkout/mercadopago'
      preLoaderRoute: typeof ApiCheckoutMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  DistribuidorRoute: DistribuidorRoute,
  EmpezarNegocioRoute: EmpezarNegocioRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  ResumenEmpresaRoute: ResumenEmpresaRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PagoExitoRoute: PagoExitoRoute,
  PagoFalloRoute: PagoFalloRoute,
  PagoPendienteRoute: PagoPendienteRoute,
  PeptidosCiudadRoute: PeptidosCiudadRoute,
  ProductosSlugRoute: ProductosSlugRoute,
  ProductosIndexRoute: ProductosIndexRoute,
  ApiCheckoutMercadopagoRoute: ApiCheckoutMercadopagoRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
