/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResumenEmpresaRouteImport } from './routes/resumen-empresa'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as PoliticaDevolucionesRouteImport } from './routes/politica-devoluciones'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmpezarNegocioRouteImport } from './routes/empezar-negocio'
import { Route as DistribuidorRouteImport } from './routes/distribuidor'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductosSlugRouteImport } from './routes/productos.$slug'
import { Route as PeptidosCiudadRouteImport } from './routes/peptidos.$ciudad'
import { Route as PagoPendienteRouteImport } from './routes/pago.pendiente'
import { Route as PagoFalloRouteImport } from './routes/pago.fallo'
import { Route as PagoExitoRouteImport } from './routes/pago.exito'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCarritosRouteImport } from './routes/admin.carritos'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiCheckoutVerifyRouteImport } from './routes/api.checkout.verify'
import { Route as ApiCheckoutCreateOrderRouteImport } from './routes/api.checkout.create-order'
import { Route as AdminPedidosIdRouteImport } from './routes/admin.pedidos.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumenEmpresaRoute = ResumenEmpresaRouteImport.update({
  id: '/resumen-empresa',
  path: '/resumen-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDevolucionesRoute = PoliticaDevolucionesRouteImport.update({
  id: '/politica-devoluciones',
  path: '/politica-devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpezarNegocioRoute = EmpezarNegocioRouteImport.update({
  id: '/empezar-negocio',
  path: '/empezar-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidorRoute = DistribuidorRouteImport.update({
  id: '/distribuidor',
  path: '/distribuidor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductosSlugRoute = ProductosSlugRouteImport.update({
  id: '/productos/$slug',
  path: '/productos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PeptidosCiudadRoute = PeptidosCiudadRouteImport.update({
  id: '/peptidos/$ciudad',
  path: '/peptidos/$ciudad',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoPendienteRoute = PagoPendienteRouteImport.update({
  id: '/pago/pendiente',
  path: '/pago/pendiente',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoFalloRoute = PagoFalloRouteImport.update({
  id: '/pago/fallo',
  path: '/pago/fallo',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoExitoRoute = PagoExitoRouteImport.update({
  id: '/pago/exito',
  path: '/pago/exito',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarritosRoute = AdminCarritosRouteImport.update({
  id: '/carritos',
  path: '/carritos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCheckoutVerifyRoute = ApiCheckoutVerifyRouteImport.update({
  id: '/api/checkout/verify',
  path: '/api/checkout/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutCreateOrderRoute = ApiCheckoutCreateOrderRouteImport.update({
  id: '/api/checkout/create-order',
  path: '/api/checkout/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPedidosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/distribuidor': typeof DistribuidorRoute
  '/empezar-negocio': typeof EmpezarNegocioRoute
  '/login': typeof LoginRoute
  '/politica-devoluciones': typeof PoliticaDevolucionesRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/resumen-empresa': typeof ResumenEmpresaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/carritos': typeof AdminCarritosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/fallo': typeof PagoFalloRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/peptidos/$ciudad': typeof PeptidosCiudadRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/api/checkout/create-order': typeof ApiCheckoutCreateOrderRoute
  '/api/checkout/verify': typeof ApiCheckoutVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/distribuidor': typeof DistribuidorRoute
  '/empezar-negocio': typeof EmpezarNegocioRoute
  '/login': typeof LoginRoute
  '/politica-devoluciones': typeof PoliticaDevolucionesRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/resumen-empresa': typeof ResumenEmpresaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/carritos': typeof AdminCarritosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/fallo': typeof PagoFalloRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/peptidos/$ciudad': typeof PeptidosCiudadRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/productos': typeof ProductosIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/api/checkout/create-order': typeof ApiCheckoutCreateOrderRoute
  '/api/checkout/verify': typeof ApiCheckoutVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/distribuidor': typeof DistribuidorRoute
  '/empezar-negocio': typeof EmpezarNegocioRoute
  '/login': typeof LoginRoute
  '/politica-devoluciones': typeof PoliticaDevolucionesRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/resumen-empresa': typeof ResumenEmpresaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/carritos': typeof AdminCarritosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/fallo': typeof PagoFalloRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/peptidos/$ciudad': typeof PeptidosCiudadRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/api/checkout/create-order': typeof ApiCheckoutCreateOrderRoute
  '/api/checkout/verify': typeof ApiCheckoutVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/carrito'
    | '/checkout'
    | '/como-funciona'
    | '/contacto'
    | '/distribuidor'
    | '/empezar-negocio'
    | '/login'
    | '/politica-devoluciones'
    | '/preguntas-frecuentes'
    | '/resumen-empresa'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/carritos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/pedidos'
    | '/blog/$slug'
    | '/pago/exito'
    | '/pago/fallo'
    | '/pago/pendiente'
    | '/peptidos/$ciudad'
    | '/productos/$slug'
    | '/admin/'
    | '/productos/'
    | '/admin/pedidos/$id'
    | '/api/checkout/create-order'
    | '/api/checkout/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/carrito'
    | '/checkout'
    | '/como-funciona'
    | '/contacto'
    | '/distribuidor'
    | '/empezar-negocio'
    | '/login'
    | '/politica-devoluciones'
    | '/preguntas-frecuentes'
    | '/resumen-empresa'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/carritos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/pedidos'
    | '/blog/$slug'
    | '/pago/exito'
    | '/pago/fallo'
    | '/pago/pendiente'
    | '/peptidos/$ciudad'
    | '/productos/$slug'
    | '/admin'
    | '/productos'
    | '/admin/pedidos/$id'
    | '/api/checkout/create-order'
    | '/api/checkout/verify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/carrito'
    | '/checkout'
    | '/como-funciona'
    | '/contacto'
    | '/distribuidor'
    | '/empezar-negocio'
    | '/login'
    | '/politica-devoluciones'
    | '/preguntas-frecuentes'
    | '/resumen-empresa'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/carritos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/pedidos'
    | '/blog/$slug'
    | '/pago/exito'
    | '/pago/fallo'
    | '/pago/pendiente'
    | '/peptidos/$ciudad'
    | '/productos/$slug'
    | '/admin/'
    | '/productos/'
    | '/admin/pedidos/$id'
    | '/api/checkout/create-order'
    | '/api/checkout/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CarritoRoute: typeof CarritoRoute
  CheckoutRoute: typeof CheckoutRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  DistribuidorRoute: typeof DistribuidorRoute
  EmpezarNegocioRoute: typeof EmpezarNegocioRoute
  LoginRoute: typeof LoginRoute
  PoliticaDevolucionesRoute: typeof PoliticaDevolucionesRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  ResumenEmpresaRoute: typeof ResumenEmpresaRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PagoExitoRoute: typeof PagoExitoRoute
  PagoFalloRoute: typeof PagoFalloRoute
  PagoPendienteRoute: typeof PagoPendienteRoute
  PeptidosCiudadRoute: typeof PeptidosCiudadRoute
  ProductosSlugRoute: typeof ProductosSlugRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
  ApiCheckoutCreateOrderRoute: typeof ApiCheckoutCreateOrderRoute
  ApiCheckoutVerifyRoute: typeof ApiCheckoutVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumen-empresa': {
      id: '/resumen-empresa'
      path: '/resumen-empresa'
      fullPath: '/resumen-empresa'
      preLoaderRoute: typeof ResumenEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-devoluciones': {
      id: '/politica-devoluciones'
      path: '/politica-devoluciones'
      fullPath: '/politica-devoluciones'
      preLoaderRoute: typeof PoliticaDevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empezar-negocio': {
      id: '/empezar-negocio'
      path: '/empezar-negocio'
      fullPath: '/empezar-negocio'
      preLoaderRoute: typeof EmpezarNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor': {
      id: '/distribuidor'
      path: '/distribuidor'
      fullPath: '/distribuidor'
      preLoaderRoute: typeof DistribuidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/productos/$slug': {
      id: '/productos/$slug'
      path: '/productos/$slug'
      fullPath: '/productos/$slug'
      preLoaderRoute: typeof ProductosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peptidos/$ciudad': {
      id: '/peptidos/$ciudad'
      path: '/peptidos/$ciudad'
      fullPath: '/peptidos/$ciudad'
      preLoaderRoute: typeof PeptidosCiudadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/pendiente': {
      id: '/pago/pendiente'
      path: '/pago/pendiente'
      fullPath: '/pago/pendiente'
      preLoaderRoute: typeof PagoPendienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/fallo': {
      id: '/pago/fallo'
      path: '/pago/fallo'
      fullPath: '/pago/fallo'
      preLoaderRoute: typeof PagoFalloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/exito': {
      id: '/pago/exito'
      path: '/pago/exito'
      fullPath: '/pago/exito'
      preLoaderRoute: typeof PagoExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carritos': {
      id: '/admin/carritos'
      path: '/carritos'
      fullPath: '/admin/carritos'
      preLoaderRoute: typeof AdminCarritosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/checkout/verify': {
      id: '/api/checkout/verify'
      path: '/api/checkout/verify'
      fullPath: '/api/checkout/verify'
      preLoaderRoute: typeof ApiCheckoutVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/create-order': {
      id: '/api/checkout/create-order'
      path: '/api/checkout/create-order'
      fullPath: '/api/checkout/create-order'
      preLoaderRoute: typeof ApiCheckoutCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
  }
}

interface AdminPedidosRouteChildren {
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
}

const AdminPedidosRouteChildren: AdminPedidosRouteChildren = {
  AdminPedidosIdRoute: AdminPedidosIdRoute,
}

const AdminPedidosRouteWithChildren = AdminPedidosRoute._addFileChildren(
  AdminPedidosRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCarritosRoute: typeof AdminCarritosRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminPedidosRoute: typeof AdminPedidosRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCarritosRoute: AdminCarritosRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminPedidosRoute: AdminPedidosRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CarritoRoute: CarritoRoute,
  CheckoutRoute: CheckoutRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  DistribuidorRoute: DistribuidorRoute,
  EmpezarNegocioRoute: EmpezarNegocioRoute,
  LoginRoute: LoginRoute,
  PoliticaDevolucionesRoute: PoliticaDevolucionesRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  ResumenEmpresaRoute: ResumenEmpresaRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PagoExitoRoute: PagoExitoRoute,
  PagoFalloRoute: PagoFalloRoute,
  PagoPendienteRoute: PagoPendienteRoute,
  PeptidosCiudadRoute: PeptidosCiudadRoute,
  ProductosSlugRoute: ProductosSlugRoute,
  ProductosIndexRoute: ProductosIndexRoute,
  ApiCheckoutCreateOrderRoute: ApiCheckoutCreateOrderRoute,
  ApiCheckoutVerifyRoute: ApiCheckoutVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
